import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

import Navbar from "@/components/navbar";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ClerkProvider>
      <html style={{
        width: "100vw",
        height: "100vh",
        scrollBehavior: "smooth",
        overflowX: "hidden",
      }} lang="en">
        <body
          style={{ width: "100vw", height: "100vh" }}
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-950`}
        >
          {/* <Navbar brand="Mony"/> */}
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
