import type { Metadata } from "next";
import Sidebar from "@/components/sidebar";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html>
        <body className="w-[100vw] bg-zinc-950">
            <div className="flex w-full  p-2 gap-2">
                <div className="w-[20%]">
                    <Sidebar brand="Mony"/>
                </div>
                <div className="p-2 w-[80%]">
                    {children}
                </div>
            </div>
        </body>
    </html>
  );
}
